# Generated by Django 4.2.2 on 2023-07-16 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date_of_creation_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 13, 38, 8, 11915), null=True, verbose_name='Дата создания'),
        ),
    ]
