# Generated by Django 4.2.2 on 2023-07-16 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 22, 56, 43, 883635), null=True, verbose_name='Дата создания'),
        ),
    ]
