# Generated by Django 4.2.2 on 2023-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default='2023-06-24', null=True, verbose_name='Дата создания'),
        ),
    ]
